# This is a basic workflow to help you get started with Actions

name: Run - Creator - Full

# Controls when the workflow will run
on:
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP_NAME: apim-devops  # Replace this value
  API_MANAGEMENT_SERVICE_NAME: apiops # Replace this value  
  TMPDIR: "./"
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2   
        with:
          fetch-depth: 0
          
      # Download the Creator binary
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: publish-creator.yml
          name: creator
          repo: seenu433/apiops 

      - name: Run creator
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          AZURE_RESOURCE_GROUP_NAME: ${{ env.AZURE_RESOURCE_GROUP_NAME }}
          API_MANAGEMENT_SERVICE_OUTPUT_FOLDER_PATH: "."
        run: |
          chmod +x ./creator
          ./creator
